version: '2.2'
services:
  weather_conditions:
    build: refresh_weather_conditions/
    depends_on:
      db:
        condition: service_healthy
  db:
    build: db/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", ' psql -h localhost -U pi -w -d shinyweather -c "SELECT * FROM forecast;"']
      interval: 20s
      timeout: 5s
      retries: 10
  web:
    build: 
      context: webservice/
      network: host
    ports:
      - "5000:5000"
      - "80:80"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
    privileged: true
    depends_on:
      db:
        condition: service_healthy
